In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import plotly.express as px
import seaborn as sns
sns.set()

In [4]:
df = pd.read_csv('/healthcare_dataset.csv')

In [5]:
df.columns = df.columns.str.strip().str.lower().str.replace(" ", "_")

In [6]:
df.name = df.name.str.strip().str.capitalize()

In [7]:
df.head()

,name,age,gender,blood_type,medical_condition,date_of_admission,doctor,hospital,insurance_provider,billing_amount,room_number,admission_type,discharge_date,medication,test_results
0,Bobby jackson,30,Male,B-,Cancer,2024-01-31,Matthew Smith,Sons and Miller,Blue Cross,18856.281306,328,Urgent,2024-02-02,Paracetamol,Normal
1,Leslie terry,62,Male,A+,Obesity,2019-08-20,Samantha Davies,Kim Inc,Medicare,33643.327287,265,Emergency,2019-08-26,Ibuprofen,Inconclusive
2,Danny smith,76,Female,A-,Obesity,2022-09-22,Tiffany Mitchell,Cook PLC,Aetna,27955.096079,205,Emergency,2022-10-07,Aspirin,Normal
3,Andrew watts,28,Female,O+,Diabetes,2020-11-18,Kevin Wells,"Hernandez Rogers and Vang,",Medicare,37909.782410,450,Elective,2020-12-18,Ibuprofen,Abnormal
4,Adrienne bell,43,Female,AB+,Cancer,2022-09-19,Kathleen Hanna,White-White,Aetna,14238.317814,458,Urgent,2022-10-09,Penicillin,Abnormal

In [8]:
df.describe(include='object')

,name,gender,blood_type,medical_condition,date_of_admission,doctor,hospital,insurance_provider,admission_type,discharge_date,medication,test_results
count,55500,55500,55500,55500,55500,55500,55500,55500,55500,55500,55500,55500
unique,40235,2,8,6,1827,40341,39876,5,3,1856,5,3
top,Michael williams,Male,A-,Arthritis,2024-03-16,Michael Smith,LLC Smith,Cigna,Elective,2020-03-15,Lipitor,Abnormal
freq,24,27774,6969,9308,50,27,44,11249,18655,53,11140,18627

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 55500 entries, 0 to 55499
Data columns (total 15 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   name                55500 non-null  object
 1   age                 55500 non-null  int64
 2   gender              55500 non-null  object
 3   blood_type          55500 non-null  object
 4   medical_condition   55500 non-null  object
 5   date_of_admission   55500 non-null  object
 6   doctor              55500 non-null  object
 7   hospital            55500 non-null  object
 8   insurance_provider  55500 non-null  object
 9   billing_amount      55500 non-null  float64
 10  room_number         55500 non-null  int64
 11  admission_type      55500 non-null  object
 12  discharge_date      55500 non-null  object
 13  medication          55500 non-null  object
 14  test_results        55500 non-null  object
dtypes: float64(1), int64(2), object(12)
memory usage: 6.4+ MB

In [10]:
df.isna().sum()

name                  0
age                   0
gender                0
blood_type            0
medical_condition     0
date_of_admission     0
doctor                0
hospital              0
insurance_provider    0
billing_amount        0
room_number           0
admission_type        0
discharge_date        0
medication            0
test_results          0
dtype: int64

In [11]:
df.discharge_date = pd.to_datetime(df.discharge_date, errors='coerce')
df.date_of_admission = pd.to_datetime(df.date_of_admission, errors='coerce')

In [12]:
df.dtypes

name                          object
age                            int64
gender                        object
blood_type                    object
medical_condition             object
date_of_admission     datetime64[ns]
doctor                        object
hospital                      object
insurance_provider            object
billing_amount               float64
room_number                    int64
admission_type                object
discharge_date        datetime64[ns]
medication                    object
test_results                  object
dtype: object

In [13]:
# removin the negative values in billing_amount
df = df[df.billing_amount >= 0]

In [14]:
# Distribution of Age
fig_age  = px.histogram(
    df,
    x='age',
    nbins=30,
    title='Age Distribution Of Patients',
    labels={"age": "Age"},
    marginal="box",
    color_discrete_sequence=["green"]
)
fig_age.show()

In [15]:
# Gender Distribution
fig_gender = px.pie(
    df,
    names='gender',
    title='Gender Distribution',
    color_discrete_sequence=px.colors.qualitative.Set2
)

fig_gender.show()

In [16]:
# Billing amount distribution
fig_billing = px.box(
    df,
    y='billing_amount',
    title='Billing Amount Distribution',
    labels={
        'billing_amount': 'Billing Amount'
    },
    color_discrete_sequence=['red']
)
fig_billing.show()

In [17]:
# most Common medical Conditions
medical_counts = df.medical_condition.value_counts()
fig_medical = px.bar(
    x=medical_counts.index,
    y=medical_counts.values,
    title='Top Medical Conditions',
    labels={
        'x': 'Medical Condition',
        'y': 'Count'
    },
    color_discrete_sequence=['green']

)
fig_medical.show()

In [18]:
# Admission Type Breakdown
fig_admissions = px.pie(
    df,
    names='admission_type',
    title='Admission Type Distribution',
    color_discrete_sequence=px.colors.qualitative.Set2
)

fig_admissions.show()

In [19]:
# Top Hospitals by Patients Counts
def hospital_viz(num_of_hospitals:int):
    hospital_counts = df.hospital.value_counts().nlargest(num_of_hospitals)
    fig_hospital = px.bar(
        x=hospital_counts.index,
        y=hospital_counts.values,
        title=f'Top {num_of_hospitals} Hospitals by Patients Counts',
        labels={
            'x': 'Hospital',
            'y': 'Number of Patients'
        },
        color_discrete_sequence=px.colors.qualitative.Set2
    )

    return fig_hospital.show()

hospital_viz(6)

In [20]:
df.insurance_provider.value_counts()

insurance_provider
Cigna               11225
Medicare            11132
UnitedHealthcare    11106
Blue Cross          11043
Aetna               10886
Name: count, dtype: int64

In [21]:
fig_insurance = px.pie(
    df,
    names='insurance_provider',
    title='Insurance Providers Distribution',
    color_discrete_sequence=px.colors.qualitative.Set3
)

fig_insurance.show()